#167733812 Create helper method for invalid user parameters
andela/colossus-backend pull request #22
Opened 2019-08-22 12:26 UTC by girlking

#### What does this PR do?
Setsup descriptive signup/Registration validation errors

#### Description of Task to be completed?
* Create a new branch for the feature
* Create file  /helpers/ValidationHelper.js
*  Import the required module - express validator
* Create helper method for invalid user parameters

#### How should this be manually tested?
A descriptive signup/Registration validation errors if you create a password that is less than 8 characters

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#167733812](https://www.pivotaltracker.com/story/show/167733812)

#### Screenshots (if appropriate)

#### Questions:
N/A

2019-08-22 13:39 UTC, fegzycole commented
Looks good

2019-08-22 15:00 UTC, Ileriayo requested changes
I noticed that  you pushed the `dist` folder. This must have been created when you ran `npm start` which is meant for production. Endeavor to use `npm run start-dev` for development. The `dist` folder is not supposed to be checked into version control. Include it in the `.gitignore` file and force push again.

2019-08-22 23:10 UTC, girlking commented
> I noticed that you pushed the `dist` folder. This must have been created when you ran `npm start` which is meant for production. Endeavor to use `npm run start-dev` for development. The `dist` folder is not supposed to be checked into version control. Include it in the `.gitignore` file and force push again.

2019-08-22 23:22 UTC, girlking commented
> > I noticed that you pushed the `dist` folder. This must have been created when you ran `npm start` which is meant for production. Endeavor to use `npm run start-dev` for development. The `dist` folder is not supposed to be checked into version control. Include it in the `.gitignore` file and force push again.

I have removed the dist folder. Thank you

2019-08-23 08:37 UTC, Ileriayo approved these changes
1. Great job setting up validations @girlking.

2. The class name `Helpers` & module name `Helper.js` is too generic. Try renaming it in your next PR.

2019-08-23 13:07 UTC, Ileriayo approved these changes
Good job. However, you have to resolve pending merge conflicts @girlking.

2019-08-23 13:07 UTC, Ileriayo commented on .env.example
> +DATABASE_DEV=
Thanks for adding this file.

2019-08-26 15:32 UTC, kingsley-einstein commented
Looks ok

2019-08-26 15:43 UTC, EziamakaNV approved these changes
Looking good!

2019-08-26 15:48 UTC, merged